### ISSUE TITLE
Add GOOD holders in subgraphs

### ISSUE THREAD

**Issue by drptiago** [GoodDollar/GoodSubGraphs#7]
We want to show information about GOOD tokens in the dashboard.

Now we have a mockup ( using GDX) of how this dashboard will be:

https://datastudio.google.com/u/0/reporting/825de2c4-a34d-47d9-b73e-bc8630a24419/page/p_bwuxwz14vc

For achieve this we need:

- Address holding the tokens
- Quantity of token in each address

**Comment by sirpy** [comment]
added a graph called GoodDollarFuse2
https://thegraph.com/hosted-service/subgraph/gooddollar/gooddollarfuse2
GoodBalance is per user record containing GOOD data
User is a per user record containing invite stats

**Comment by drptiago** [comment]
I believe we had an error in this subgraph @sirpy 

![image](https://user-images.githubusercontent.com/62208156/185997665-117e7356-6196-48e9-aa47-96c0a0c99e66.png)
